export const SELECT_LIST_NAME = 'SELECT_LIST_NAME'
export const CHANGE_LIST_NAME = 'CHANGE_LIST_NAME'
export const REMOVE_LIST_NAME = 'REMOVE_LIST_NAME'
export const CREATE_LIST_NAME = 'CREATE_LIST_NAME'
export const SHOW_CREATE_LIST_NAME = 'SHOW_CREATE_LIST_NAME'
export const HIDE_CREATE_LIST_NAME = 'HIDE_CREATE_LIST_NAME'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'